DATA:
  data_root: '../FSSD-12/'
  train_list: './data_list/train/fold0_defect.txt'
  val_list: './data_list/val/fold0_defect.txt'
  classes: 2


TRAIN:
  layers: 50
  sync_bn: False
  train_h: 200
  train_w: 200
  val_size: 200
  scale_min: 0.9    # minimum random scale
  scale_max: 1.1    # maximum random scale
  rotate_min: -10   # minimum random rotate
  rotate_max: 10    # maximum random rotate
  zoom_factor: 8
  ignore_label: 255
  padding_label: 255
  aux_weight: 1.0
  # train_gpu: [0]
  workers: 0        # data loader workers 2->4
  batch_size: 2     # batch size for training
  batch_size_val: 1
  base_lr: 0.0025
  epochs: 200
  start_epoch: 0
  power: 0.9        # 0 means no decay
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed: 1998
  print_freq: 5
  save_freq: 5
#  save_path: exp/SSD/fold0_resnet50/model_5shot   # model saved path
#  shot: 5
  save_path: exp/SSD/fold0_vgg16/model_1shot   # model saved path
  shot: 1
  weight:                                         # load weight for fine-tuning or testing
  resume:                                         # path to latest checkpoint (default: none)
  evaluate: True
  split: 0
  vgg: True # use vgg as backbone or not
#  ppm_scales: [66, 33, 16, 8]
  ppm_scales: [60, 30, 15, 8]
  fix_random_seed_val: True
  warmup: False
  resized_val: True
  ori_resize: True  # use original label for evaluation


