DATA:
  data_root: 'C:/dataset/FSSD-12/'
  val_list: './data_list/val/fold1_defect.txt'
  split: 1
  classes: 2
  weight: "E:/ys/CPANet_similar/exp/SSD/fold0_resnet50/model_1shot/final.pth"  # load weight for fine-tuning or testing

  save_path: 'exp/test_pth/'   # model saved path
#  save_path: exp/SSD/fold0_resnet50/model_5shot   # model saved path
TRAIN:
  train: False
  evaluate: True

  layers: 'convtiny'

  # sync_bn: False
  train_h: 200
  train_w: 200
  val_size: 200
  scale_min: 0.9    # minimum random scale
  scale_max: 1.1    # maximum random scale
  rotate_min: -10   # minimum random rotate
  rotate_max: 10    # maximum random rotate
  # zoom_factor: 8
  ignore_label: 255
  padding_label: 255
  # aux_weight: 1.0
  # train_gpu: [0]
  workers: 2        # data loader workers 2->4
  batch_size: 2     # batch size for training
  batch_size_val: 1
  base_lr: 0.0025
  epochs: 201
  start_epoch: 0
  power: 0.9        # 0 means no decay
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed: 1998
  print_freq: 5
  save_freq: 5

#  shot: 5
  shot: 1
  resume:                                         # path to latest checkpoint (default: none)
  vgg: False # use vgg as backbone or not
#  ppm_scales: [66, 33, 16, 8]
  ppm_scales: [60, 30, 15, 8]
  fix_random_seed_val: True
  warmup: False
  resized_val: True
  ori_resize: True  # use original label for evaluation


