DATA:
  data_root: 'C:/dataset/defect/'
  val_list: 'C:/dataset/defect/img.txt'
  save_path: 'exp/SSD/test_tfevents/'   # model saved path
  weight: "exp/SSD/fold2_resnet50/model_1shot/final.pth"  # load weight for fine-tuning or testing
  split: 999
  
  layers: 50 #'convtiny'
  vgg: False # use vgg as backbone or not
  classes: 2
  train: False
  evaluate: True
  workers: 2        # data loader workers 2->4
  batch_size_val: 1
  manual_seed: 1998
  print_freq: 10
#  shot: 5
  shot: 1
  fix_random_seed_val: True
  resized_val: True
  ori_resize: True  # use original label for evaluation

TRAIN:

  train_h: 200
  train_w: 200
  val_size: 200
  scale_min: 0.9    # minimum random scale
  scale_max: 1.1    # maximum random scale
  rotate_min: -10   # minimum random rotate
  rotate_max: 10    # maximum random rotate
  ignore_label: 255
  padding_label: 255




